---

- name: Installing common packages
  hosts: common
  vars:
    home: "/home/vagrant"
  roles:
    - common

- name: Install Ruby and Rails
  hosts: rails
  vars:
    home: "/home/vagrant"
    ruby_latest_version: 2.2.2
    rails_latest_version: 4.2.3
  roles:
    - rails

- name: Install Database (MySQL and MongoDB)
  hosts: db
  roles:
    - db

- name: Install Cache Server (Redis)
  hosts: cache
  roles:
    - cache

- name: Install nodejs
  hosts: nodejs
  vars:
    home: "/home/vagrant"
    node_latest_version: 0.12.4
  roles:
    - nodejs

- name: Install Development tools
  hosts: dev
  vars:
    home: "/home/vagrant"
  roles:
    - devtools
