---
# Using gem to install latest rails

- name: check rails installed
  command: test -x {{ home }}/.rbenv/shims/rails
  register: rails_present
  ignore_errors: yes
  
- name: install version {{rails_latest_version}}
  shell: ". {{ home }}/.profile && gem install rails -v {{ rails_latest_version }}"
  when: rails_present | failed

- name: rebuild the shim binaries
  shell: ". {{ home }}/.profile && rbenv rehash"
  when: rails_present | failed

- name: list installed Rails versions
  shell: ". {{ home }}/.profile && rails -v"
  register: rails_versions
- debug: var=rails_versions

