---
# Install mysql
- name: Install packages for MySQL
  apt: name={{ item }} state=present update_cache=yes
  sudo: yes
  with_items:
  - mysql-server
  - mysql-client
  - libmysqlclient-dev
  - python-mysqldb
